spring:
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 39.97.253.19:8848
    #        namespace: 558260dc-2b0a-40f0-a100-1225f1dd9e4c
    sentinel:
      transport:
        #        指定sentinel控制台地址
        dashboard: localhost:8080
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      # 抽样率，默认是 0.1（10%）
      probability: 1.0




  datasource:
    url: jdbc:mysql://39.97.253.19:3306/content_center?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: xxqroot
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 5001

info:
  app:
    name: content-center
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

# 饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: user-center

# 配置类 配置细粒度 随机策略
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


rocketmq:
  name-server: 39.97.253.19:9876
  producer:
    #必须制定group
    group: test-group

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        # 配置feign的拦截器，让token可以在各个微服务之间传递
        requestInterceptors:
          - com.soft1851.content.center.feignclient.TokenInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

jwt:
  secret: mmmmmmmmnnnnnnnnccccccccxxxxxxxx2
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

logging:
  level:
    com.alibaba.nacos: error
    org.springframework.cloud.sleuth: debug

