server:
  port: 6001

# Mybatis
mybatis:
  type-aliases-package: com.soft1851.course.center.domain.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://39.97.253.19:3306/course_center?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: xxqroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
